# Generated by Django 5.2.10 on 2026-02-05 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_phananh_dia_chi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ tên người gửi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email liên hệ')),
                ('sdt', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('chu_de', models.CharField(choices=[('tai_khoan', '🔑 Lỗi tài khoản / Đăng nhập'), ('sai_hien_trang', '⚠️ Báo cáo sai hiện trạng (Đã xử lý nhưng thực tế chưa xong)'), ('huong_dan', '📘 Cần hướng dẫn sử dụng'), ('gop_y', '💡 Góp ý tính năng mới'), ('khac', '💬 Khác')], default='khac', max_length=50)),
                ('noi_dung', models.TextField(verbose_name='Nội dung chi tiết')),
                ('da_xu_ly', models.BooleanField(default=False, verbose_name='Đã xử lý xong?')),
                ('phan_hoi_admin', models.TextField(blank=True, null=True, verbose_name='Admin trả lời')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('nguoi_gui', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
