# Generated by Django 5.2.10 on 2026-03-05 12:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_alter_hotro_options_alter_hotro_chu_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='phananh',
            name='vi_tri',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Tọa độ chuẩn GIS'),
        ),
    ]
