# Generated by Django 5.2.10 on 2026-03-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_alter_profile_so_dien_thoai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
    ]
