# Generated by Django 5.2.10 on 2026-04-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_alter_profile_so_dien_thoai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phananh',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ/Tên đường'),
        ),
    ]
