# Generated by Django 5.2.10 on 2026-04-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_alter_phananh_dia_chi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GioiThieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tiêu đề chính')),
                ('mo_ta_ngan', models.TextField(verbose_name='Mô tả ngắn (Slogan)')),
                ('noi_dung_chi_tiet', models.TextField(verbose_name='Nội dung chi tiết')),
                ('hinh_anh', models.ImageField(upload_to='gioi_thieu/', verbose_name='Hình ảnh minh họa')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quản lý Giới thiệu',
                'verbose_name_plural': 'Quản lý Giới thiệu',
            },
        ),
    ]
