# Generated by Django 5.2.10 on 2026-04-26 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_alter_gioithieu_noi_dung_chi_tiet'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuanHuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_quan', models.CharField(max_length=100, verbose_name='Tên Quận/Huyện')),
            ],
            options={
                'verbose_name': 'Quận/Huyện',
                'verbose_name_plural': 'Danh sách Quận/Huyện',
            },
        ),
        migrations.AddField(
            model_name='phananh',
            name='quan_huyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.quanhuyen', verbose_name='Thuộc Quận/Huyện'),
        ),
        migrations.AddField(
            model_name='profile',
            name='quan_quan_ly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.quanhuyen', verbose_name='Quận/Huyện quản lý (Dành cho nhân viên)'),
        ),
    ]
