# Generated by Django 5.2.10 on 2026-04-26 13:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_quanhuyen_phananh_quan_huyen_profile_quan_quan_ly'),
    ]

    operations = [
        migrations.AddField(
            model_name='quanhuyen',
            name='mau_sac',
            field=models.CharField(default='#3388ff', help_text='Mã màu Hex (VD: #3388ff)', max_length=7),
        ),
        migrations.AddField(
            model_name='quanhuyen',
            name='ranh_gioi',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Ranh giới'),
        ),
        migrations.AlterField(
            model_name='quanhuyen',
            name='ten_quan',
            field=models.CharField(max_length=100, verbose_name='Tên Khu Vực'),
        ),
    ]
