# Generated by Django 5.2.10 on 2026-04-26 13:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0019_quanhuyen_mau_sac_quanhuyen_ranh_gioi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quanhuyen',
            name='ranh_gioi',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Ranh giới'),
        ),
    ]
