# Generated by Django 5.2.10 on 2026-05-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0020_alter_quanhuyen_ranh_gioi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chuyen_mon',
            field=models.CharField(choices=[('an_ninh', 'An ninh & Cứu nạn'), ('dien_luc', 'Điện lực (EVN)'), ('cap_thoat_nuoc', 'Cấp thoát nước'), ('cay_xanh', 'Công viên Cây xanh'), ('chieu_sang', 'Chiếu sáng Đô thị'), ('giao_thong', 'Hạ tầng Giao thông'), ('tong_hop', 'Quản lý Tổng hợp')], default='tong_hop', max_length=50, verbose_name='Chuyên môn phụ trách'),
        ),
    ]
