# Generated by Django 5.2.10 on 2026-05-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_profile_chuyen_mon'),
    ]

    operations = [
        migrations.AddField(
            model_name='phananh',
            name='loai_su_co',
            field=models.CharField(choices=[('an_ninh', 'An ninh & Cứu nạn'), ('dien_luc', 'Điện lực (EVN)'), ('cap_thoat_nuoc', 'Cấp thoát nước'), ('cay_xanh', 'Công viên Cây xanh'), ('chieu_sang', 'Chiếu sáng Đô thị'), ('giao_thong', 'Hạ tầng Giao thông'), ('khac', 'Khác')], default='khac', max_length=50, verbose_name='Thuộc lĩnh vực'),
        ),
    ]
