# Generated by Django 5.2.10 on 2026-01-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhanAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('mo_ta', models.TextField(verbose_name='Mô tả chi tiết')),
                ('du_lieu_toa_do', models.TextField(verbose_name='Danh sách tọa độ')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='hien_truong/', verbose_name='Ảnh hiện trường')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('dang_xu_ly', 'Đang xử lý'), ('da_xu_ly', 'Đã xử lý xong')], default='cho_duyet', max_length=20, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Tin Phản Ánh',
                'verbose_name_plural': 'Danh sách Phản Ánh',
            },
        ),
    ]
