# Generated by Django 5.2.10 on 2026-02-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='phananh',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ/Tên đường'),
        ),
    ]
