# Generated by Django 5.2.10 on 2026-02-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_hotro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotro',
            options={'verbose_name': 'Yêu cầu Hỗ trợ', 'verbose_name_plural': 'Danh sách Hỗ trợ'},
        ),
        migrations.AlterField(
            model_name='hotro',
            name='chu_de',
            field=models.CharField(choices=[('tai_khoan', '🔑 Lỗi tài khoản / Đăng nhập'), ('sai_hien_trang', '⚠️ Báo cáo sai hiện trạng'), ('huong_dan', '📘 Cần hướng dẫn sử dụng'), ('gop_y', '💡 Góp ý tính năng mới'), ('khac', '💬 Khác')], default='khac', max_length=50),
        ),
    ]
