# Generated by Django 5.2.10 on 2026-03-29 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_phananh_vi_tri'),
    ]

    operations = [
        migrations.CreateModel(
            name='HinhAnhPhanAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to='hien_truong/chi_tiet/', verbose_name='Ảnh chi tiết')),
                ('ngay_tai_len', models.DateTimeField(auto_now_add=True)),
                ('phan_anh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_anh', to='maps.phananh')),
            ],
            options={
                'verbose_name': 'Hình Ảnh Phản Ánh',
                'verbose_name_plural': 'Danh sách Hình Ảnh Chi Tiết',
            },
        ),
    ]
