# Generated by Django 5.2.10 on 2026-03-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_hinhanhphananh'),
    ]

    operations = [
        migrations.AddField(
            model_name='phananh',
            name='da_xoa',
            field=models.BooleanField(default=False, verbose_name='Đã chuyển vào thùng rác'),
        ),
        migrations.AddField(
            model_name='phananh',
            name='ngay_xoa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa'),
        ),
    ]
