# Generated by Django 5.2.10 on 2026-04-21 00:42

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_gioithieu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gioithieu',
            name='hinh_anh',
        ),
        migrations.AlterField(
            model_name='gioithieu',
            name='noi_dung_chi_tiet',
            field=ckeditor.fields.RichTextField(verbose_name='Nội dung chi tiết'),
        ),
        migrations.CreateModel(
            name='AnhGioiThieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to='gioi_thieu/', verbose_name='Hình ảnh Slide')),
                ('mo_ta_anh', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả ảnh')),
                ('gioi_thieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maps.gioithieu')),
            ],
            options={
                'verbose_name': 'Hình ảnh Giới thiệu',
                'verbose_name_plural': 'Danh sách ảnh Slide',
            },
        ),
    ]
