# Generated by Django 5.2.10 on 2026-04-21 02:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_remove_gioithieu_hinh_anh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gioithieu',
            name='noi_dung_chi_tiet',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội dung chi tiết'),
        ),
    ]
